/**
 * 代码高亮主题扩充（本文件由 scripts/convert-wenyan-themes.ts 生成；重跑：npm run convert:themes）。
 * 全部转换自项目内 node_modules/highlight.js/styles 的官方主题 CSS（BSD-3-Clause），
 * 未经过 wenyan——highlight.js 本就是官方主题源，省一层依赖也无 license 问题。
 */
import type { CodeThemeDef } from './highlight'

/* GitHub 深色（highlight.js 官方 github-dark.css） */
const githubDark: CodeThemeDef = {
  id: 'github-dark',
  label: 'GitHub 深色',
  background: '#0d1117',
  color: '#c9d1d9',
  tokens: {
    'doctag': 'color:#ff7b72;',
    'keyword': 'color:#ff7b72;',
    'template-tag': 'color:#ff7b72;',
    'template-variable': 'color:#ff7b72;',
    'type': 'color:#ff7b72;',
    'language': 'color:#ff7b72;',
    'title': 'color:#d2a8ff;',
    'class': 'color:#d2a8ff;',
    'inherited': 'color:#d2a8ff;',
    'function': 'color:#d2a8ff;',
    'attr': 'color:#79c0ff;',
    'attribute': 'color:#79c0ff;',
    'literal': 'color:#79c0ff;',
    'meta': 'color:#79c0ff;',
    'number': 'color:#79c0ff;',
    'operator': 'color:#79c0ff;',
    'variable': 'color:#79c0ff;',
    'selector-attr': 'color:#79c0ff;',
    'selector-class': 'color:#79c0ff;',
    'selector-id': 'color:#79c0ff;',
    'regexp': 'color:#a5d6ff;',
    'string': 'color:#a5d6ff;',
    'built_in': 'color:#ffa657;',
    'symbol': 'color:#ffa657;',
    'comment': 'color:#8b949e;',
    'code': 'color:#8b949e;',
    'formula': 'color:#8b949e;',
    'name': 'color:#7ee787;',
    'quote': 'color:#7ee787;',
    'selector-tag': 'color:#7ee787;',
    'selector-pseudo': 'color:#7ee787;',
    'subst': 'color:#c9d1d9;',
    'section': 'color:#1f6feb;font-weight:bold;',
    'bullet': 'color:#f2cc60;',
    'emphasis': 'color:#c9d1d9;font-style:italic;',
    'strong': 'color:#c9d1d9;font-weight:bold;',
    'addition': 'color:#aff5b4;background:#033a16;',
    'deletion': 'color:#ffdcd7;background:#67060c;',
  },
}

/* Atom One 浅色（highlight.js 官方 atom-one-light.css） */
const atomOneLight: CodeThemeDef = {
  id: 'atom-one-light',
  label: 'Atom One 浅色',
  background: '#fafafa',
  color: '#383a42',
  tokens: {
    'comment': 'color:#a0a1a7;font-style:italic;',
    'quote': 'color:#a0a1a7;font-style:italic;',
    'doctag': 'color:#a626a4;',
    'keyword': 'color:#a626a4;',
    'formula': 'color:#a626a4;',
    'section': 'color:#e45649;',
    'name': 'color:#e45649;',
    'selector-tag': 'color:#e45649;',
    'deletion': 'color:#e45649;',
    'subst': 'color:#e45649;',
    'literal': 'color:#0184bb;',
    'string': 'color:#50a14f;',
    'regexp': 'color:#50a14f;',
    'addition': 'color:#50a14f;',
    'attribute': 'color:#50a14f;',
    'attr': 'color:#986801;',
    'variable': 'color:#986801;',
    'template-variable': 'color:#986801;',
    'type': 'color:#986801;',
    'selector-class': 'color:#986801;',
    'selector-attr': 'color:#986801;',
    'selector-pseudo': 'color:#986801;',
    'number': 'color:#986801;',
    'symbol': 'color:#4078f2;',
    'bullet': 'color:#4078f2;',
    'link': 'color:#4078f2;text-decoration:underline;',
    'meta': 'color:#4078f2;',
    'selector-id': 'color:#4078f2;',
    'title': 'color:#4078f2;',
    'built_in': 'color:#c18401;',
    'class': 'color:#c18401;',
    'emphasis': 'font-style:italic;',
    'strong': 'font-weight:bold;',
  },
}

/* Dracula（highlight.js 官方 base16/dracula.css） */
const dracula: CodeThemeDef = {
  id: 'dracula',
  label: 'Dracula',
  background: '#282936',
  color: '#e9e9f4',
  tokens: {
    'comment': 'color:#626483;',
    'tag': 'color:#62d6e8;',
    'subst': 'color:#e9e9f4;',
    'punctuation': 'color:#e9e9f4;',
    'operator': 'color:#e9e9f4;',
    'bullet': 'color:#ea51b2;',
    'variable': 'color:#ea51b2;',
    'template-variable': 'color:#ea51b2;',
    'selector-tag': 'color:#ea51b2;',
    'name': 'color:#ea51b2;',
    'deletion': 'color:#ea51b2;',
    'symbol': 'color:#b45bcf;',
    'number': 'color:#b45bcf;',
    'link': 'color:#b45bcf;',
    'attr': 'color:#b45bcf;',
    'constant': 'color:#b45bcf;',
    'literal': 'color:#b45bcf;',
    'title': 'color:#00f769;',
    'class': 'color:#00f769;',
    'strong': 'font-weight:bold;color:#00f769;',
    'code': 'color:#ebff87;',
    'addition': 'color:#ebff87;',
    'inherited': 'color:#ebff87;',
    'string': 'color:#ebff87;',
    'built_in': 'color:#a1efe4;',
    'doctag': 'color:#a1efe4;',
    'quote': 'color:#a1efe4;',
    'atrule': 'color:#a1efe4;',
    'regexp': 'color:#a1efe4;',
    'attribute': 'color:#62d6e8;',
    'function': 'color:#62d6e8;',
    'section': 'color:#62d6e8;',
    'type': 'color:#b45bcf;',
    'template-tag': 'color:#b45bcf;',
    'keyword': 'color:#b45bcf;',
    'emphasis': 'color:#b45bcf;font-style:italic;',
    'meta': 'color:#00f769;',
    'meta-keyword': 'font-weight:bold;',
  },
}

/* Solarized 浅色（highlight.js 官方 base16/solarized-light.css） */
const solarizedLight: CodeThemeDef = {
  id: 'solarized-light',
  label: 'Solarized 浅色',
  background: '#fdf6e3',
  color: '#586e75',
  tokens: {
    'comment': 'color:#839496;',
    'tag': 'color:#657b83;',
    'subst': 'color:#586e75;',
    'punctuation': 'color:#586e75;',
    'operator': 'color:#586e75;',
    'bullet': 'color:#dc322f;',
    'variable': 'color:#dc322f;',
    'template-variable': 'color:#dc322f;',
    'selector-tag': 'color:#dc322f;',
    'name': 'color:#dc322f;',
    'deletion': 'color:#dc322f;',
    'symbol': 'color:#cb4b16;',
    'number': 'color:#cb4b16;',
    'link': 'color:#cb4b16;',
    'attr': 'color:#cb4b16;',
    'constant': 'color:#cb4b16;',
    'literal': 'color:#cb4b16;',
    'title': 'color:#b58900;',
    'class': 'color:#b58900;',
    'strong': 'font-weight:bold;color:#b58900;',
    'code': 'color:#859900;',
    'addition': 'color:#859900;',
    'inherited': 'color:#859900;',
    'string': 'color:#859900;',
    'built_in': 'color:#2aa198;',
    'doctag': 'color:#2aa198;',
    'quote': 'color:#2aa198;',
    'atrule': 'color:#2aa198;',
    'regexp': 'color:#2aa198;',
    'attribute': 'color:#268bd2;',
    'function': 'color:#268bd2;',
    'section': 'color:#268bd2;',
    'type': 'color:#6c71c4;',
    'template-tag': 'color:#6c71c4;',
    'keyword': 'color:#6c71c4;',
    'emphasis': 'color:#6c71c4;font-style:italic;',
    'meta': 'color:#d33682;',
    'meta-keyword': 'font-weight:bold;',
  },
}

/* Solarized 深色（highlight.js 官方 base16/solarized-dark.css） */
const solarizedDark: CodeThemeDef = {
  id: 'solarized-dark',
  label: 'Solarized 深色',
  background: '#002b36',
  color: '#93a1a1',
  tokens: {
    'comment': 'color:#657b83;',
    'tag': 'color:#839496;',
    'subst': 'color:#93a1a1;',
    'punctuation': 'color:#93a1a1;',
    'operator': 'color:#93a1a1;',
    'bullet': 'color:#dc322f;',
    'variable': 'color:#dc322f;',
    'template-variable': 'color:#dc322f;',
    'selector-tag': 'color:#dc322f;',
    'name': 'color:#dc322f;',
    'deletion': 'color:#dc322f;',
    'symbol': 'color:#cb4b16;',
    'number': 'color:#cb4b16;',
    'link': 'color:#cb4b16;',
    'attr': 'color:#cb4b16;',
    'constant': 'color:#cb4b16;',
    'literal': 'color:#cb4b16;',
    'title': 'color:#b58900;',
    'class': 'color:#b58900;',
    'strong': 'font-weight:bold;color:#b58900;',
    'code': 'color:#859900;',
    'addition': 'color:#859900;',
    'inherited': 'color:#859900;',
    'string': 'color:#859900;',
    'built_in': 'color:#2aa198;',
    'doctag': 'color:#2aa198;',
    'quote': 'color:#2aa198;',
    'atrule': 'color:#2aa198;',
    'regexp': 'color:#2aa198;',
    'attribute': 'color:#268bd2;',
    'function': 'color:#268bd2;',
    'section': 'color:#268bd2;',
    'type': 'color:#6c71c4;',
    'template-tag': 'color:#6c71c4;',
    'keyword': 'color:#6c71c4;',
    'emphasis': 'color:#6c71c4;font-style:italic;',
    'meta': 'color:#d33682;',
    'meta-keyword': 'font-weight:bold;',
  },
}

/* Xcode（highlight.js 官方 xcode.css） */
const xcode: CodeThemeDef = {
  id: 'xcode',
  label: 'Xcode',
  background: '#fff',
  color: 'black',
  tokens: {
    'comment': 'color:#007400;',
    'quote': 'color:#007400;',
    'tag': 'color:#aa0d91;',
    'attribute': 'color:#aa0d91;',
    'keyword': 'color:#aa0d91;',
    'selector-tag': 'color:#aa0d91;',
    'literal': 'color:#aa0d91;',
    'name': 'color:#aa0d91;',
    'variable': 'color:#3F6E74;',
    'template-variable': 'color:#3F6E74;',
    'code': 'color:#c41a16;',
    'string': 'color:#c41a16;',
    'regexp': 'color:#0E0EFF;',
    'link': 'color:#0E0EFF;',
    'title': 'color:#1c00cf;',
    'symbol': 'color:#1c00cf;',
    'bullet': 'color:#1c00cf;',
    'number': 'color:#1c00cf;',
    'section': 'color:#643820;',
    'meta': 'color:#643820;',
    'class': 'color:#5c2699;',
    'type': 'color:#5c2699;',
    'built_in': 'color:#5c2699;',
    'params': 'color:#5c2699;',
    'attr': 'color:#836C28;',
    'subst': 'color:#000;',
    'formula': 'background:#eee;font-style:italic;',
    'addition': 'background:#baeeba;',
    'deletion': 'background:#ffc8bd;',
    'selector-id': 'color:#9b703f;',
    'selector-class': 'color:#9b703f;',
    'doctag': 'font-weight:bold;',
    'strong': 'font-weight:bold;',
    'emphasis': 'font-style:italic;',
  },
}

export const EXTRA_CODE_THEMES: CodeThemeDef[] = [githubDark, atomOneLight, dracula, solarizedLight, solarizedDark, xcode]
