/**
 * wenyan 公众号排版主题移植（本文件由 scripts/convert-wenyan-themes.ts 生成，
 * 手工微调后如需重新生成请先 diff；重跑：npm run convert:themes）。
 *
 * 主题 CSS 来源：caol64/wenyan-core（https://github.com/caol64/wenyan-core，Apache-2.0），
 * 其中 lapis 源自 YiNNx/typora-theme-lapis（作者 YiNN），其余各主题原作者见各段注释。
 *
 * 转换约定：
 * - CSS 变量已展开；各主题强调色映射为可调主色 ${primary}，字号按与正文的比例挂到 ${fs}
 * - wenyan 的 ::before/::after 装饰、nth-child 斑马纹无法写进 style 属性，已按公众号约束舍弃
 *   （公众号后台会剥掉 <style>，wenyan 自己内联发布时同样丢，不要用 <style> 去救）
 * - wenyan 渲染器把标题文字包 span，wemark 不包，h2 span 的徽章样式已并入 h2 本体
 * - 代码块样式由 lib/wemark/highlight.ts 全权接管，未从 wenyan 采集 pre 规则
 */
import type { ThemeDef } from './themes'

/* ==================== 青金 lapis —— typora-theme-lapis（作者 YiNN，https://github.com/YiNNx/typora-theme-lapis） ==================== */
const lapis: ThemeDef = {
  id: 'lapis',
  label: '青金',
  desc: '实心徽章二级标题，青金石学术蓝',
  styles: ({ primary, fontSize: fs }) => ({
    container: `line-height:1.75;font-size:${fs}px;font-family:-apple-system,BlinkMacSystemFont,'Helvetica Neue','PingFang SC','Hiragino Sans GB','Microsoft YaHei',sans-serif;color:#40464f;text-align:left;word-break:break-word;`,
    h1: `padding:0px;color:${primary};margin:1.2em 0 1em;text-align:center;font-size:${Math.round(fs * 1.5)}px;`,
    h2: `padding:1px 12.5px;color:#ffffff;margin:1.2em 0 1em;border-radius:4px;display:inline-block;background-color:${primary};font-size:${Math.round(fs * 1.3)}px;`,
    h3: `padding:0px;color:${primary};margin:1.2em 0 1em;font-size:${Math.round(fs * 1.3)}px;`,
    h4: `font-weight:normal;padding:0px;color:${primary};margin:1.2em 0 1em;font-size:${Math.round(fs * 1.2)}px;`,
    h5: `font-weight:normal;padding:0px;color:${primary};margin:1.2em 0 1em;font-size:${Math.round(fs * 1.2)}px;`,
    h6: `font-weight:normal;padding:0px;color:${primary};margin:1.2em 0 1em;font-size:${Math.round(fs * 1.2)}px;`,
    p: `margin:1em 0;`,
    blockquote: `display:block;font-size:${Math.round(fs * 0.9)}px;border-left:3px solid ${primary};padding:0.5em 1em;margin:0;background:#f6f8fa;color:#40464f;`,
    blockquote_p: `margin:0.5em 0;`,
    ul: `padding-left:1rem;margin-left:1rem;font-size:${Math.round(fs * 0.9)}px;list-style-type:disc;`,
    ol: `padding-left:1rem;margin-left:1rem;font-size:${Math.round(fs * 0.9)}px;list-style-type:decimal;`,
    li: `margin:0.4em 0;`,
    code_inline: `color:${primary};font-size:${Math.round(fs * 0.9)}px;font-weight:normal;word-wrap:break-word;padding:2px 4px 2px;border-radius:3px;margin:2px;background-color:#f6f8fa;word-break:break-all;`,
    a: `word-wrap:break-word;color:${primary};`,
    strong: `color:${primary};`,
    em: `padding:0 3px 0 0;`,
    del: `color:#888888;text-decoration:line-through;`,
    hr: `margin-top:20px;margin-bottom:20px;border:0;border-top:2px solid #eef2f5;border-radius:2px;`,
    img: `max-width:100%;height:auto;margin:0 auto;display:block;`,
    figure: `margin:1.4em 0;`,
    figcaption: `margin-top:0.5em;color:#888888;font-size:${Math.round(fs * 0.85)}px;text-align:center;`,
    table: `display:table;text-align:left;overflow-x:auto;border-collapse:collapse;margin:1.4em auto;max-width:100%;table-layout:fixed;overflow:auto;word-wrap:break-word;word-break:break-all;`,
    th: `border:1px solid #d9dfe4;padding:9px 12px;font-size:${Math.round(fs * 0.75)}px;line-height:22px;vertical-align:top;text-align:center;font-weight:bold;color:${primary};background:#f7f7f7;`,
    td: `border:1px solid #d9dfe4;padding:9px 12px;font-size:${Math.round(fs * 0.75)}px;line-height:22px;vertical-align:top;`,
    footnotes_hr: `margin:3em 0 1em;border:none;border-top:1px dashed ${primary}66;`,
    footnotes_title: `margin:0 0 0.5em;color:${primary};font-size:${Math.round(fs * 0.95)}px;font-weight:bold;`,
    footnote_item: `margin:0;font-size:${Math.round(fs * 0.9)}px;`,
    sup: `color:${primary};font-size:${Math.round(fs * 0.75)}px;margin-left:2px;`,
  }),
}

/* ==================== 玉米 maize —— typora-maize-theme（作者 BEATREE，https://github.com/BEATREE/typora-maize-theme） ==================== */
const maize: ThemeDef = {
  id: 'maize',
  label: '玉米',
  desc: '暖黄强调 + 柔和圆角图片，玉米暖调',
  styles: ({ primary, fontSize: fs }) => ({
    container: `line-height:1.75;font-size:${fs}px;font-family:-apple-system,BlinkMacSystemFont,'Helvetica Neue','PingFang SC','Hiragino Sans GB','Microsoft YaHei',sans-serif;color:#3f3f3f;text-align:left;word-break:break-word;`,
    h1: `margin:1.2em 0 1em;padding:0px;font-weight:bold;font-size:${Math.round(fs * 1.5)}px;`,
    h2: `margin:1.2em 0 1em;padding:3px 10px 1px;font-weight:bold;font-size:${Math.round(fs * 1.3)}px;border-left:4px solid ${primary};padding-left:10px;`,
    h3: `margin:1.2em 0 1em;padding:0px;font-weight:bold;font-size:${Math.round(fs * 1.3)}px;`,
    h4: `margin:1.2em 0 1em;padding:0px;font-weight:bold;font-size:${Math.round(fs * 1.2)}px;`,
    h5: `margin:1.2em 0 1em;padding:0px;font-weight:bold;font-size:${Math.round(fs * 1.2)}px;`,
    h6: `margin:1.2em 0 1em;padding:0px;font-weight:bold;font-size:${Math.round(fs * 1.2)}px;`,
    p: `margin:1em 0;`,
    blockquote: `margin:0;padding:10px 10px 10px 20px;font-size:${Math.round(fs * 0.9)}px;background:${primary}0d;border-left:3px solid ${primary};color:#6a737d;overflow:auto;`,
    blockquote_p: `margin:0.5em 0;`,
    ul: `padding-left:1rem;margin-left:1rem;font-size:${Math.round(fs * 0.9)}px;list-style-type:disc;`,
    ol: `padding-left:1rem;margin-left:1rem;font-size:${Math.round(fs * 0.9)}px;list-style-type:decimal;`,
    li: `margin:0.4em 0;`,
    code_inline: `word-wrap:break-word;padding:2px 4px;border-radius:4px;margin:0 2px;word-break:break-all;color:${primary};background-color:#f0f0f0;font-size:${Math.round(fs * 0.8)}px;`,
    a: `word-wrap:break-word;text-decoration:none;font-weight:bold;color:${primary};border-bottom:1px solid ${primary};`,
    strong: `color:${primary};font-weight:bold;`,
    em: `font-style:italic;`,
    del: `color:#888888;text-decoration:line-through;`,
    hr: `height:1px;padding:0;border:none;text-align:center;background-image:linear-gradient( to right, rgba(231, 93, 109, 0.3), rgba(255, 159, 150, 0.75), rgba(255, 216, 181, 0.3) );`,
    img: `max-width:100%;display:block;margin:0 auto;border-radius:5px;box-shadow:0px 4px 12px #84a1a8;border:0px;`,
    figure: `margin:1.4em 0;`,
    figcaption: `margin-top:0.5em;color:#888888;font-size:${Math.round(fs * 0.85)}px;text-align:center;`,
    table: `border-collapse:collapse;margin:1.4em auto;max-width:100%;table-layout:fixed;text-align:left;overflow:auto;display:table;word-wrap:break-word;word-break:break-all;`,
    th: `font-size:${Math.round(fs * 0.75)}px;padding:9px 12px;line-height:22px;border:1px solid ${primary}4d;vertical-align:top;font-weight:bold;color:${primary};background:${primary}0d;`,
    td: `font-size:${Math.round(fs * 0.75)}px;padding:9px 12px;line-height:22px;border:1px solid ${primary}4d;vertical-align:top;color:#222;`,
    footnotes_hr: `margin:3em 0 1em;border:none;border-top:1px dashed ${primary}66;`,
    footnotes_title: `margin:0 0 0.5em;color:${primary};font-size:${Math.round(fs * 0.95)}px;font-weight:bold;`,
    footnote_item: `margin:0;font-size:${Math.round(fs * 0.9)}px;`,
    sup: `font-weight:bold;color:${primary};font-size:${Math.round(fs * 0.75)}px;margin-left:2px;`,
  }),
}

/* ==================== 橙心 orangeheart —— typora-theme-orange-heart（作者 evgo2017，https://github.com/evgo2017/typora-theme-orange-heart） ==================== */
const orangeheart: ThemeDef = {
  id: 'orangeheart',
  label: '橙心',
  desc: '标签式二级标题 + 暖底引用块，橙心风',
  styles: ({ primary, fontSize: fs }) => ({
    container: `line-height:1.75;font-size:${fs}px;font-family:-apple-system,BlinkMacSystemFont,'Helvetica Neue','PingFang SC','Hiragino Sans GB','Microsoft YaHei',sans-serif;color:#3f3f3f;text-align:left;word-break:break-word;`,
    h1: `margin:1.2em 0 1em;padding:0px;font-weight:bold;font-size:${Math.round(fs * 1.5)}px;`,
    h2: `margin:1.2em 0 1em;padding:3px 10px 1px;font-weight:bold;font-size:${Math.round(fs * 1.3)}px;border-bottom:2px solid ${primary};display:inline-block;background:${primary};color:#ffffff;border-top-right-radius:3px;border-top-left-radius:3px;margin-right:3px;`,
    h3: `margin:1.2em 0 1em;padding:0px;font-weight:bold;font-size:${Math.round(fs * 1.3)}px;`,
    h4: `margin:1.2em 0 1em;padding:0px;font-weight:bold;font-size:${Math.round(fs * 1.2)}px;`,
    h5: `margin:1.2em 0 1em;padding:0px;font-weight:bold;font-size:${Math.round(fs * 1.1)}px;`,
    h6: `margin:1.2em 0 1em;padding:0px;font-weight:bold;font-size:${fs}px;`,
    p: `margin:1em 0;`,
    blockquote: `margin:0;display:block;font-size:${Math.round(fs * 0.9)}px;overflow:auto;border-left:3px solid ${primary};color:#6a737d;padding:10px 10px 10px 20px;margin-bottom:20px;margin-top:20px;background:${primary}0d;`,
    blockquote_p: `margin:0.5em 0;`,
    ul: `padding-left:1rem;margin-left:1rem;font-size:${Math.round(fs * 0.9)}px;list-style-type:disc;`,
    ol: `padding-left:1rem;margin-left:1rem;font-size:${Math.round(fs * 0.9)}px;list-style-type:decimal;`,
    li: `margin:0.4em 0;`,
    code_inline: `font-size:${Math.round(fs * 0.9)}px;word-wrap:break-word;padding:2px 4px;border-radius:4px;margin:0 2px;color:${primary};background-color:rgba(27, 31, 35, 0.05);word-break:break-all;`,
    a: `text-decoration:none;word-wrap:break-word;font-weight:bold;color:${primary};border-bottom:1px solid ${primary};`,
    strong: `font-weight:bold;`,
    em: `font-style:italic;`,
    del: `color:#888888;text-decoration:line-through;`,
    hr: `margin:2em 0;border:none;border-top:1px solid #e5e5e5;`,
    img: `max-width:100%;height:auto;margin:0 auto;display:block;`,
    figure: `margin:1.4em 0;`,
    figcaption: `margin-top:0.5em;color:#888888;font-size:${Math.round(fs * 0.85)}px;text-align:center;`,
    table: `border-collapse:collapse;margin:1.4em auto;max-width:100%;table-layout:fixed;text-align:left;overflow:auto;display:table;word-wrap:break-word;word-break:break-all;`,
    th: `font-size:${Math.round(fs * 0.75)}px;padding:9px 12px;line-height:22px;border:1px solid ${primary};vertical-align:top;font-weight:bold;background-color:${primary}0d;color:${primary};`,
    td: `font-size:${Math.round(fs * 0.75)}px;padding:9px 12px;line-height:22px;border:1px solid ${primary};vertical-align:top;`,
    footnotes_hr: `margin:3em 0 1em;border:none;border-top:1px dashed ${primary}66;`,
    footnotes_title: `margin:0 0 0.5em;color:${primary};font-size:${Math.round(fs * 0.95)}px;font-weight:bold;`,
    footnote_item: `margin:0;font-size:${Math.round(fs * 0.9)}px;`,
    sup: `color:${primary};font-size:${Math.round(fs * 0.75)}px;margin-left:2px;`,
  }),
}

/* ==================== 薄荷 phycat —— typora-theme-phycat（作者 sumruler，https://github.com/sumruler/typora-theme-phycat） ==================== */
const phycat: ThemeDef = {
  id: 'phycat',
  label: '薄荷',
  desc: '渐变徽章标题 + 细密行距，物理猫科普风',
  styles: ({ primary, fontSize: fs }) => ({
    container: `font-size:${fs}px;line-height:1.75;letter-spacing:1.1px;word-break:break-word;word-wrap:break-word;text-align:left;font-family:-apple-system,BlinkMacSystemFont,'Helvetica Neue','PingFang SC','Hiragino Sans GB','Microsoft YaHei',sans-serif;color:#333333;`,
    h1: `text-align:center;font-weight:bold;font-size:${Math.round(fs * 1.4)}px;`,
    h2: `color:#fff;font-size:${Math.round(fs * 1.4)}px;line-height:1.6;width:fit-content;font-weight:bold;margin:20px 0 5px;padding:1px 12.5px;border-radius:4px;background:linear-gradient(90deg,${primary},${primary}b3);background-size:200% 100%;background-position:0% 0%;display:inline-block;`,
    h3: `font-weight:bold;width:fit-content;margin:20px 0 5px;font-size:${Math.round(fs * 1.3)}px;padding-left:10px;border-left:5px solid ${primary};`,
    h4: `font-weight:bold;margin:20px 0 5px;font-size:${Math.round(fs * 1.15)}px;`,
    h5: `font-weight:bold;margin:20px 0 5px;font-size:${Math.round(fs * 1.1)}px;`,
    h6: `font-weight:bold;margin:20px 0 5px;font-size:${Math.round(fs * 1.1)}px;`,
    p: `text-align:justify;margin:10px 0;word-spacing:2px;`,
    blockquote: `font-size:${Math.round(fs * 0.86)}px;margin-left:12px;text-align:justify;padding:12px;background:${primary}14;border:0px solid ${primary};border-left-color:${primary};border-left-width:4px;border-radius:4px;line-height:26px;`,
    blockquote_p: `margin:0.5em 0;`,
    ul: `padding-left:1rem;margin-left:1rem;font-size:${Math.round(fs * 0.9)}px;list-style-type:disc;`,
    ol: `padding-left:1rem;margin-left:1rem;font-size:${Math.round(fs * 0.9)}px;list-style-type:decimal;`,
    li: `color:#333;margin:0px 6px;word-spacing:2px;line-height:2.5;`,
    code_inline: `padding:3px 3px 1px;color:${primary};background:${primary}14;border-radius:3px;letter-spacing:0.5px;`,
    a: `font-weight:bolder;text-decoration:none;border-bottom:1px solid ${primary};`,
    strong: `font-weight:bold;`,
    em: `font-style:italic;`,
    del: `text-decoration-color:${primary};`,
    hr: `height:1px;padding:0;border:none;border-top:2px solid ${primary};`,
    img: `max-width:90%;display:block;border-radius:6px;margin:10px auto;object-fit:contain;`,
    figure: `margin:1.4em 0;`,
    figcaption: `margin-top:0.5em;color:#888888;font-size:${Math.round(fs * 0.85)}px;text-align:center;`,
    table: `border-collapse:collapse;margin:1.4em auto;max-width:100%;table-layout:fixed;text-align:left;overflow:auto;display:table;word-wrap:break-word;word-break:break-all;`,
    th: `font-size:${Math.round(fs * 0.71)}px;padding:9px 12px;line-height:22px;border:1px solid ${primary};vertical-align:top;font-weight:bold;background-color:${primary}14;color:${primary};`,
    td: `font-size:${Math.round(fs * 0.71)}px;padding:9px 12px;line-height:22px;border:1px solid ${primary};vertical-align:top;`,
    footnotes_hr: `margin:3em 0 1em;border:none;border-top:1px dashed ${primary}66;`,
    footnotes_title: `margin:0 0 0.5em;color:${primary};font-size:${Math.round(fs * 0.95)}px;font-weight:bold;`,
    footnote_item: `margin:0;font-size:${Math.round(fs * 0.9)}px;`,
    sup: `color:${primary};font-size:${Math.round(fs * 0.75)}px;margin-left:2px;`,
  }),
}

/* ==================== 正红 pie —— typora-theme-pie（作者 kevinzhao2233，https://github.com/kevinzhao2233/typora-theme-pie） ==================== */
const pie: ThemeDef = {
  id: 'pie',
  label: '正红',
  desc: '居中虚线大标题 + 正红强调，Pie 杂志风',
  styles: ({ primary, fontSize: fs }) => ({
    container: `line-height:1.75;letter-spacing:0;font-size:${fs}px;font-family:-apple-system,BlinkMacSystemFont,'Helvetica Neue','PingFang SC','Hiragino Sans GB','Microsoft YaHei',sans-serif;color:#262626;text-align:left;word-break:break-word;`,
    h1: `margin:1.2em 0 1em;padding:0px;font-weight:bold;font-size:${Math.round(fs * 1.5)}px;text-align:center;`,
    h2: `margin:2em auto 1.4em;padding:0px;font-weight:bold;padding-left:6px;font-size:${Math.round(fs * 1.3)}px;border-left:6px solid ${primary};`,
    h3: `margin:1.2em 0 1em;padding:0px;font-weight:bold;font-size:${Math.round(fs * 1.2)}px;`,
    h4: `margin:1.2em 0 1em;padding:0px;font-weight:bold;font-size:${Math.round(fs * 1.2)}px;`,
    h5: `margin:1.2em 0 1em;padding:0px;font-weight:bold;font-size:${Math.round(fs * 1.2)}px;`,
    h6: `margin:1.2em 0 1em;padding:0px;font-weight:bold;font-size:${Math.round(fs * 1.2)}px;color:#8c8c8c;`,
    p: `margin:1em 0;word-spacing:0.05rem;text-align:justify;`,
    blockquote: `padding:24px 16px 12px;margin:24px 0 36px;font-size:${fs}px;font-style:normal;line-height:1.6;color:#8c8c8c;text-indent:0;border:none;border-left:2px solid ${primary};padding:12px 16px;`,
    blockquote_p: `margin:0.5em 0;`,
    ul: `padding-left:1rem;margin-left:1rem;font-size:${Math.round(fs * 0.9)}px;list-style-type:disc;`,
    ol: `padding-left:1rem;margin-left:1rem;font-size:${Math.round(fs * 0.9)}px;list-style-type:decimal;`,
    li: `margin:0.4em 0;`,
    code_inline: `padding:2px 4px 1px;margin:0 2px;font-size:${Math.round(fs * 0.92)}px;color:${primary};background-color:${primary}14;border-radius:3px;vertical-align:0.5px;`,
    a: `word-wrap:break-word;color:${primary};text-decoration:none;border-bottom:1px solid ${primary};padding:0 2px;font-weight:500;`,
    strong: `padding:0 1px;`,
    em: `padding:0 5px 0 2px;`,
    del: `color:#888888;text-decoration:line-through;`,
    hr: `box-sizing:content-box;width:100%;height:1px;padding:0;margin:46px auto 64px;overflow:hidden;background-color:${primary}99;border:0;`,
    img: `max-width:100%;display:block;margin:0 auto;border-radius:4px;`,
    figure: `margin:1.4em 0;`,
    figcaption: `margin-top:0.5em;color:#888888;font-size:${Math.round(fs * 0.85)}px;text-align:center;`,
    table: `border-collapse:collapse;margin:1.4em auto;max-width:100%;table-layout:fixed;text-align:left;overflow:auto;display:table;word-wrap:break-word;word-break:break-all;`,
    th: `font-size:${Math.round(fs * 0.75)}px;padding:9px 12px;line-height:22px;vertical-align:top;border:1px solid ${primary}99;font-weight:bold;color:${primary};background-color:${primary}14;`,
    td: `font-size:${Math.round(fs * 0.75)}px;padding:9px 12px;line-height:22px;vertical-align:top;border:1px solid ${primary}99;`,
    footnotes_hr: `margin:3em 0 1em;border:none;border-top:1px dashed ${primary}66;`,
    footnotes_title: `margin:0 0 0.5em;color:${primary};font-size:${Math.round(fs * 0.95)}px;font-weight:bold;`,
    footnote_item: `margin:0;font-size:${Math.round(fs * 0.9)}px;`,
    sup: `color:${primary};background-color:${primary}14;font-size:${Math.round(fs * 0.75)}px;margin-left:2px;`,
  }),
}

/* ==================== 紫韵 purple —— typora-purple-theme（作者 hliu202，https://github.com/hliu202/typora-purple-theme） ==================== */
const purple: ThemeDef = {
  id: 'purple',
  label: '紫韵',
  desc: '左竖线二级标题 + 淡紫引用，人文随笔风',
  styles: ({ primary, fontSize: fs }) => ({
    container: `line-height:1.75;font-size:${fs}px;font-family:-apple-system,BlinkMacSystemFont,'Helvetica Neue','PingFang SC','Hiragino Sans GB','Microsoft YaHei',sans-serif;color:#444444;text-align:left;word-break:break-word;`,
    h1: `margin:1.2em 0 1em;padding:0px;font-weight:normal;color:${primary};text-align:center;font-size:${Math.round(fs * 1.5)}px;`,
    h2: `margin:1.2em 0 1em;padding:0px;font-weight:normal;color:${primary};padding-left:0.4em;border-left:0.4em solid ${primary};border-bottom:1px solid ${primary};font-size:${Math.round(fs * 1.3)}px;`,
    h3: `margin:1.2em 0 1em;padding:0px;font-weight:normal;color:${primary};font-size:${Math.round(fs * 1.2)}px;`,
    h4: `margin:1.2em 0 1em;padding:0px;font-weight:normal;color:${primary};font-size:${Math.round(fs * 1.2)}px;`,
    h5: `margin:1.2em 0 1em;padding:0px;font-weight:normal;color:${primary};font-size:${Math.round(fs * 1.2)}px;`,
    h6: `margin:1.2em 0 1em;padding:0px;font-weight:normal;color:${primary};font-size:${Math.round(fs * 1.2)}px;`,
    p: `margin:1.5em auto;`,
    blockquote: `margin:0;border-left:0.3em solid ${primary}33;padding-left:1em;`,
    blockquote_p: `margin:0.5em 0;`,
    ul: `padding-left:1rem;margin-left:1rem;font-size:${Math.round(fs * 0.9)}px;list-style-type:disc;`,
    ol: `padding-left:1rem;margin-left:1rem;font-size:${Math.round(fs * 0.9)}px;list-style-type:decimal;`,
    li: `margin:0.4em 0;`,
    code_inline: `padding:2px 4px;border-radius:0.3em;font-size:${Math.round(fs * 0.9)}px;color:${primary};background-color:${primary}0d;margin:0 2px;`,
    a: `word-wrap:break-word;border-bottom:1px solid #bbb;color:#2aa899;text-decoration:none;`,
    strong: `padding:0 2px;font-weight:bold;`,
    em: `font-style:italic;`,
    del: `color:#888888;text-decoration:line-through;`,
    hr: `margin:1.5em auto;border-top:1px solid #e7e7e7;border-left:none;border-right:none;border-bottom:none;`,
    img: `max-width:100%;height:auto;margin:0 auto;display:block;`,
    figure: `margin:1.4em 0;`,
    figcaption: `margin-top:0.5em;color:#888888;font-size:${Math.round(fs * 0.85)}px;text-align:center;`,
    table: `border-collapse:collapse;margin:1.4em auto;max-width:100%;table-layout:fixed;text-align:left;overflow:auto;display:table;word-wrap:break-word;word-break:break-all;`,
    th: `font-size:${Math.round(fs * 0.75)}px;padding:9px 12px;line-height:22px;border:1px solid ${primary}33;vertical-align:top;font-weight:bold;color:${primary};background-color:${primary}0d;`,
    td: `font-size:${Math.round(fs * 0.75)}px;padding:9px 12px;line-height:22px;border:1px solid ${primary}33;vertical-align:top;`,
    footnotes_hr: `margin:3em 0 1em;border:none;border-top:1px dashed ${primary}66;`,
    footnotes_title: `margin:0 0 0.5em;color:${primary};font-size:${Math.round(fs * 0.95)}px;font-weight:bold;`,
    footnote_item: `margin:0;font-size:${Math.round(fs * 0.9)}px;`,
    sup: `color:${primary};background-color:${primary}0d;font-size:${Math.round(fs * 0.75)}px;margin-left:2px;`,
  }),
}

/* ==================== 彩虹 rainbow —— typora-theme-rainbow（作者 thezbm，https://github.com/thezbm/typora-theme-rainbow） ==================== */
const rainbow: ThemeDef = {
  id: 'rainbow',
  label: '彩虹',
  desc: '粉彩色块标题 + 多彩表格，轻快活泼',
  styles: ({ primary, fontSize: fs }) => ({
    container: `line-height:1.75;font-size:${fs}px;font-family:-apple-system,BlinkMacSystemFont,'Helvetica Neue','PingFang SC','Hiragino Sans GB','Microsoft YaHei',sans-serif;color:#3f3f3f;text-align:left;word-break:break-word;`,
    h1: `margin:1.2em 0 1em;padding:0px;font-weight:bold;font-size:${Math.round(fs * 1.5)}px;text-align:center;text-shadow:0.15em 0.15em 0.3em rgb(187, 187, 187);`,
    h2: `margin:1.2em 0 1em;padding:0px;font-weight:bold;font-size:${Math.round(fs * 1.3)}px;background-color:${primary}1f;color:rgb(102, 102, 102);padding-left:1em;padding-right:1em;border-left:0.5em solid ${primary}66;border-radius:0.4em;display:inline-block;`,
    h3: `margin:1.2em 0 1em;padding:0px;font-weight:bold;font-size:${Math.round(fs * 1.3)}px;text-decoration:underline double ${primary}66;text-decoration-thickness:0.15em;`,
    h4: `margin:1.2em 0 1em;padding:0px;font-weight:bold;font-size:${Math.round(fs * 1.2)}px;text-decoration:underline dotted ${primary}66;text-decoration-thickness:0.2em;`,
    h5: `margin:1.2em 0 1em;padding:0px;font-weight:bold;`,
    h6: `margin:1.2em 0 1em;padding:0px;font-weight:bold;`,
    p: `margin:1em 0;`,
    blockquote: `font-size:${Math.round(fs * 0.9)}px;margin:0 1em;color:rgb(102, 102, 102);border-left:0.25em solid rgb(169, 202, 255);padding:0.5em 1em 0.6em 1em;`,
    blockquote_p: `margin:0;`,
    ul: `padding-left:1rem;margin-left:1rem;font-size:${Math.round(fs * 0.9)}px;list-style-type:disc;`,
    ol: `padding-left:1rem;margin-left:1rem;font-size:${Math.round(fs * 0.9)}px;list-style-type:decimal;`,
    li: `margin:0.4em 0;`,
    code_inline: `margin-left:0.25em;margin-right:0.25em;padding:0.05em 0.3em;border-radius:0.4em;box-shadow:0.13em 0.13em 0.26em rgb(197, 197, 197);font-size:${Math.round(fs * 0.9)}px;`,
    a: `word-wrap:break-word;color:${primary};`,
    strong: `font-weight:bold;`,
    em: `font-style:italic;`,
    del: `color:#888888;text-decoration:line-through;`,
    hr: `margin-top:2em;margin-bottom:2em;background-color:rgb(226, 226, 226);height:0.13em;border:0;`,
    img: `max-width:100%;height:auto;margin:0 auto;display:block;border-radius:5px;box-shadow:0.15em 0.15em 0.5em rgb(150, 150, 150);`,
    figure: `margin:1.4em 0;`,
    figcaption: `margin-top:0.5em;color:#888888;font-size:${Math.round(fs * 0.85)}px;text-align:center;`,
    table: `border-collapse:collapse;border:0.25em solid rgb(255, 235, 211);margin:1.4em auto;max-width:100%;table-layout:fixed;text-align:left;overflow:auto;display:table;word-wrap:break-word;word-break:break-all;`,
    th: `background-color:rgb(255, 243, 228);font-size:${Math.round(fs * 0.75)}px;text-align:center;border:0.13em dashed rgb(255, 235, 211);padding:9px 12px;line-height:22px;vertical-align:top;color:#222;`,
    td: `font-size:${Math.round(fs * 0.75)}px;text-align:center;border:0.13em dashed rgb(255, 235, 211);padding:9px 12px;line-height:22px;vertical-align:top;color:#222;`,
    footnotes_hr: `margin:3em 0 1em;border:none;border-top:1px dashed ${primary}66;`,
    footnotes_title: `margin:0 0 0.5em;color:${primary};font-size:${Math.round(fs * 0.95)}px;font-weight:bold;`,
    footnote_item: `margin:0;font-size:${Math.round(fs * 0.9)}px;`,
    sup: `color:${primary};font-size:${Math.round(fs * 0.75)}px;margin-left:2px;`,
  }),
}

export const WENYAN_THEMES: ThemeDef[] = [lapis, maize, orangeheart, phycat, pie, purple, rainbow]
